Bayron
CEEINF-UTFSM/ceeinf-web-backend pull request #17
Opened 2020-10-31 02:46 UTC by BayronValenzuela

#14 - Blog API
## Propósito
Que el usuario pueda crear publicaciones.
## Alcance
Se generó un endpoint para las publicaciones

2020-10-31 02:47 UTC, Legutier commented on apps/blog/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE)
:^) 👏  eri selknam

2020-10-31 02:50 UTC, LaTortugaR commented on config/settings.py
> +AUTH_USER_MODEL = "users.User"
El newline uwu

2020-10-31 02:51 UTC, Legutier requested changes
cambios pequeños pero necesarios

2020-10-31 02:51 UTC, Legutier commented on apps/blog_api/serializers.py
> +        fields = ['id', 'title', 'content', 'published_on', 'user']
```suggestion
        fields = (
            'id',
            'title',
            'content', 
            'published_on',
            'user',
        )
```

2020-10-31 02:51 UTC, Legutier commented on config/urls.py
> +    path('', include('apps.blog_api.urls')),
```suggestion
    path('blog_api/', include('apps.blog_api.urls')),
```

2020-11-07 00:12 UTC, Legutier approved these changes
approved, saludos cordiales

2020-11-07 00:14 UTC, merged